version: '2'
services:

  traefik:
    image: traefik:v1.7.4-alpine
    hostname: traefik.lab.com
    environment:
      TZ: Asia/Jakarta
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --logLevel='DEBUG'
      --api.dashboard=true
      --InsecureSkipVerify=true
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --defaultentrypoints='http,https'
      --docker
      --docker.exposedbydefault=true
      --docker.watch=true
      --docker.swarmmode=false
      --docker.endpoint='unix:///var/run/docker.sock'
    networks:
      auth_net:
      service_net:
    labels:
      traefik.enable: true
  
  keycloak_db:
    image: postgres:11.2-alpine
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_ROOT_PASSWORD=password
    networks:
      auth_net:
    volumes:
      - keycloak_db_data_vol:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  keycloak:
    image: jboss/keycloak:7.0.1
    hostname: keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    networks:
      auth_net:
    depends_on: 
      - traefik
      - keycloak_db
    labels:
      - traefik.port=8443
      - traefik.frontend.rule=Host:auth.lab.com
      - traefik.protocol=https
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
  
  keycloak-gatekeeper:
    image: keycloak/keycloak-gatekeeper:7.0.0
    labels:
     - "traefik.port=3000"
     - "traefik.frontend.rule=Host:service1.lab.com"
     - "traefik.protocol=http"
    restart: always
    depends_on: 
     - keycloak
    networks:
      service_net:
    external_links:
      - traefik:auth.lab.com
    volumes:
      - ./keycloak-gatekeeper/keycloak-gatekeeper.conf:/etc/keycloak-gatekeeper.conf
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak-gatekeeper.conf
  
  service_1:
    image: containous/whoami
    networks:
      service_net:
    depends_on: 
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  service_net:
  auth_net:

volumes: 
  keycloak_db_data_vol:
